TASK0:
  name: VQA
  type: VL-classifier
  loss: BCEWithLogitLoss
  task_id: 1
  dataroot: __ROOT__/datasets/VQA/
  train_features_h5path1: __ROOT__/datasets/coco/coco_trainval_resnet101_faster_rcnn_genome.lmdb
  eval_features_h5path1: __ROOT__/datasets/coco/coco_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 16
  max_region_num: 100
#  batch_size: 256
  batch_size: 128
#  eval_batch_size: 1024
  eval_batch_size: 128
  train_split: trainval
  val_split: minval
  lr: 0.00004
  num_epoch: 20
TASK1:
  name: VCR_Q-A
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 6
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 60
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK2:
  name: VCR_QA-R
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 7
  dataroot: data/VCR
  features_h5path1: data/VCR/VCR_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/VCR/VCR_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: data/VCR/train.jsonl
  val_annotations_jsonpath: data/VCR/val.jsonl
  max_seq_length: 80
  max_region_num: 100
  batch_size: 16
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK3:
  name: RetrievalFlickr30k
  type: VL-logit
  loss: CrossEntropyLoss
  task_id: 9
  dataroot: __ROOT__/datasets/flickr30k
  train_features_h5path1: __ROOT__/datasets/flickr30k/flickr30k_resnet101_faster_rcnn_genome.lmdb
  eval_features_h5path1: __ROOT__/datasets/flickr30k/flickr30k_test_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: ''
  train_annotations_jsonpath: __ROOT__/datasets/flickr30k/all_data_final_train_2014.jsonline
  train_val_annotations_jsonpath: __ROOT__/datasets/flickr30k/all_data_final_val_set0_2014.jsonline
  eval_val_annotations_jsonpath: __ROOT__/datasets/flickr30k/all_data_final_test_set0_2014.jsonline
  max_seq_length: 30
  max_region_num: 100
#  batch_size: 64
  batch_size: 32
  train_split: train
  val_split: val
  lr: 0.00002
  num_epoch: 20
TASK4:
  name: refcoco+
  type: V-logit
  loss: BCEWithLogitLoss
  task_id: 11
  dataroot: data/referExpression
  features_h5path1: data/referExpression/refcoco+/refcoco+_resnet101_faster_rcnn_genome.lmdb
  features_h5path2: data/referExpression/refcoco+/refcoco+_gt_resnet101_faster_rcnn_genome.lmdb
  train_annotations_jsonpath: ''
  val_annotations_jsonpath: ''
  max_seq_length: 20
  max_region_num: 100
  batch_size: 256
  eval_batch_size: 1024
  train_split: train
  val_split: val
  lr: 0.00004
  num_epoch: 30