# Setup-dependent-flags
default_root_dir: /cw/working-gimli/nathan/devlbert_ckpts/
from_pretrained: /cw/working-gimli/nathan/devlbert_ckpts/devlbert_base_real_try_4_again/pytorch_model_2.bin
output_dir: /cw/working-gimli/nathan/devlbert_ckpts

# Other flags
accelerator: ddp
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
baseline: false
benchmark: false
bert_model: bert-base-uncased
check_val_every_n_epoch: 1
checkpoint_callback: true
checkpoint_period: 100
config_file: config/bert_base_6layer_6conect.json
continue_training: true
debug: false
deterministic: false
distributed: false
distributed_backend: null
do_lower_case: true
enable_pl_optimizer: null
fast_dev_run: 1
flush_logs_every_n_steps: 100
fp16: false
freeze: -1
gpus: -1
gradient_accumulation_steps: 1
gradient_clip_val: 0
img_weight: 1
learning_rate: 0.0001
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
local_rank: -1
log_every_n_steps: 50
log_gpu_memory: null
logger: true
loss_scale: 0
max_epochs: 24
max_seq_length: 36
max_steps: null
min_epochs: null
min_steps: null
mini: false
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
no_cuda: false
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_train_epochs: 12.0
num_workers: 1
on_memory: false
overfit_batches: 0.0
precision: 32
predict_feature: false
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
save_name: pl_devlbert_repro
seed: 42
shuffle: false
start_epoch: 0
stochastic_weight_avg: false
sync_batchnorm: false
terminate_on_nan: false
track_grad_norm: -1
train_batch_size: 2
train_file: data/training
truncated_bptt_steps: null
use_chuncks: 0
val_check_interval: 1.0
validation_file: data/validation
warmup_proportion: 0.1
weights_save_path: null
weights_summary: top
without_coattention: false
world_size: 2
