# Setup-dependent-flags
from_pretrained: bert-base-uncased

trainer:
  default_root_dir: null
  accelerator: null
  accumulate_grad_batches: 1
  amp_backend: native
  amp_level: O2
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: true
  benchmark: false
  callbacks: null
  check_val_every_n_epoch: 1
  checkpoint_callback: true
  deterministic: false
  distributed_backend: null
  fast_dev_run: false
  flush_logs_every_n_steps: 100
  gpus: null
  gradient_clip_val: 0
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  log_gpu_memory: null
  logger: true
  max_epochs: 12
  max_steps: null
  min_epochs: 12
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: 1
  num_sanity_val_steps: 2
  overfit_batches: 0.0
  plugins: null
  precision: 32
  prepare_data_per_node: true
  process_position: 0
  profiler: null
  progress_bar_refresh_rate: null
  reload_dataloaders_every_epoch: false
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  stochastic_weight_avg: false
  sync_batchnorm: false
  terminate_on_nan: false
  tpu_cores: 8
  track_grad_norm: -1
  truncated_bptt_steps: null
  val_check_interval: 1.0
  weights_save_path: null
  weights_summary: top
baseline: false
bert_model: bert-base-uncased
checkpoint_period: 3600
config: null
config_file: config/bert_base_6layer_6conect.json
continue_training: false
debug: false
distributed: false
do_lower_case: true
fp16: false
freeze: -1
gradient_accumulation_steps: 1
img_weight: 1
learning_rate: 0.0001
local_rank: -1
loss_scale: 0
max_seq_length: 36
mini: false
no_cuda: false
num_workers: 0
on_memory: false
predict_feature: false
save_name: pl_devlbert_repro
seed: 42
shuffle: false
start_epoch: 0
train_batch_size: 256
train_file: data/training
use_chuncks: 0
validation_file: data/validation
warmup_proportion: 0.1
without_coattention: false
world_size: 2
